### ISSUE TITLE
 An error, ERR_HTTP_HEADERS_SENT, has occurred.

### ISSUE THREAD

**Issue by shimar** [vriad/next-firebase-ssr#1]
Hi, I'm shimar.
Thank you for a very nice example.

I tried to run this in my environment.
Then, ERR_HTTP_HEADERS_SENT has occurred when the link "Go to authenticated route" in top page clicked.

Do you know what caused it?

↓、This is the output to the terminal when an error occurs
```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:543:11)
    at DevServer.sendHTML (/Users/shimar/developments/repos/github.com/vriad/next-firebase-ssr/node_modules/next/dist/server/next-dev-server.js:31:5)
    at DevServer.render (/Users/shimar/developments/repos/github.com/vriad/next-firebase-ssr/node_modules/next/dist/next-server/server/next-server.js:56:37)
    at async Object.fn (/Users/shimar/developments/repos/github.com/vriad/next-firebase-ssr/node_modules/next/dist/next-server/server/next-server.js:32:107)
    at async Router.execute (/Users/shimar/developments/repos/github.com/vriad/next-firebase-ssr/node_modules/next/dist/next-server/server/router.js:38:67)
    at async DevServer.run (/Users/shimar/developments/repos/github.com/vriad/next-firebase-ssr/node_modules/next/dist/next-server/server/next-server.js:49:494)
    at async DevServer.handleRequest (/Users/shimar/developments/repos/github.com/vriad/next-firebase-ssr/node_modules/next/dist/next-server/server/next-server.js:18:101) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```
Best regard.

**Comment by stephensilber** [comment]
I managed to get around this by using the new redirect functionality in Next.js 9.5+.

You can read the RFC here: [https://github.com/vercel/next.js/discussions/14890](https://github.com/vercel/next.js/discussions/14890)

Inside of `pages/authenticated.tsx`, my `getServerSideProps` function now looks like this:

```
export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  try {
    const cookies = nookies.get(ctx);
    const token = await firebaseAdmin.auth().verifyIdToken(cookies.token);
    const { uid, email } = token;

    // the user is authenticated!
    // FETCH STUFF HERE

    return {
      props: { message: `Your email is ${email} and your UID is ${uid}.` },
    };
  } catch (err) {
    // either the `token` cookie didn't exist
    // or token verification failed
    // either way: redirect to the login page
    return { 
      redirect: {
        permanent: false,
        destination: '/login'
      }
    }
  }
};
```

Hopefully that helps

**Comment by vriad** [comment]
Just merged your PR! Thanks for that!
